### ISSUE TITLE
这是我找的最后一个能以天更新的库了

### ISSUE THREAD

**Issue by hhhllll888** [jiuliking/today#1]
希望能用上

**Comment by hhhllll888** [comment]
Traceback (most recent call last):
  File ".\index.py", line 2, in <module>
    from actions.wiseLoginService import wiseLoginService
ModuleNotFoundError: No module named 'actions'
报错了

**Comment by hhhllll888** [comment]
WARNING: Target directory E:\learning\today\beautifulsoup4-4.9.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\bs4 already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\certifi already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\certifi-2021.10.8.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\chardet already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\chardet-4.0.0.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\Crypto already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\idna already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\idna-2.10.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\lxml already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\pyasn1 already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\pyasn1-0.4.8.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\pycryptodome-3.10.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\pyDes-2.0.1-py3.8.egg-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\pyDes.py already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\PyYAML-5.4.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\QcloudApi already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\requests already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\requests-2.25.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\requests_toolbelt already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\requests_toolbelt-0.9.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\rsa already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\rsa-4.7.2.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\soupsieve already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\soupsieve-2.3.1.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\tencentcloud already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\tencentcloud_sdk_python-3.0.65.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\urllib3 already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\urllib3-1.26.3.dist-info already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\_yaml already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\__pycache__ already exists. Specify --upgrade to force replacement.
WARNING: Target directory E:\learning\today\bin already exists. Specify --upgrade to force replacement.

**Comment by jiuliking** [comment]
这个是我从https://github.com/CarltonHere/auto-cpdaily备份的，我不是程序员，解决不了你的问题，可以去原仓库提，这个项目是可以用的，待会我会把这个删掉，省的耽误你们

**Comment by jiuliking** [comment]
如果你看到请回复一下，你回复后我就删掉

**Comment by jiuliking** [comment]
前几天上传的时候没注意到，漏了一个文件夹。。。

**Comment by hhhllll888** [comment]
哦，我也不是程序员，我在找能用的自动今日校园签到脚本，其他脚本要么不支持云函数，要么太麻烦，谢谢了
